apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: incometax
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkZW1vdWRlbXkwMS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwTmFYTmhhV052TVRJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson