apiVersion: v1
kind: Service
metadata:
  name: incometax-service
  namespace: incometax
spec:
  type: NodePort
  selector:
    app: incometax-rtp
  ports:
    - nodePort: 30082
      port: 8000
      targetPort: 8000